name: Auto-commit latest package versions
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  update-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install semver jinja2
      - name: Run autoupdate.py
        run: ./autoupdate.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: "Auto-update package versions"
